print("How old are you?", end = ' ')
age = input()
print('How tall are you?', end = ' ')
height = input()
print('How much do you weigh?', end= ' ')
weight = input()
print("Where do/did you attend school?", end =' ')
school = input()
print(f"So, you're {age} old, {height} tall, you're '{weight} heavy, and you attend {school}. Nice.")